require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MyCollegeRoomie' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'MyCollegeRoomieTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper-Folly' => '2.5.3', 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        target_components = deployment_target.split

        if target_components.length > 0
          target_initial = target_components[0].to_i
          if target_initial < 9
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "9.0"
          end
        end

      end
    end

  end
end

target 'MyCollegeRoomie-tvOS' do
  # Pods for MyCollegeRoomie-tvOS

  target 'MyCollegeRoomie-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end
